# Generated by Django 4.1.3 on 2023-02-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('num_of_pages', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('available_on_shelf', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=1000)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_uploaded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.CharField(default=' ', max_length=1000)),
                ('upload_staff_id', models.CharField(max_length=100)),
                ('other_info', models.CharField(max_length=1000)),
                ('visibility', models.CharField(default='offlne', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='gen_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auth_token', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('lib_staff_id', models.CharField(max_length=50)),
                ('date_requested', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_collected', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('return_due_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_returned', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='lecture_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=1000)),
                ('course_code', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=1000)),
                ('date_uploaded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.CharField(default=' ', max_length=1000)),
                ('staff_id', models.CharField(max_length=50)),
                ('other_info', models.CharField(max_length=1000)),
                ('visibility', models.CharField(default='offlne', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message_type', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('date_sent', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=1000)),
                ('staff_id', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=1000)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_uploaded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('upload_staff_id', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(default=' ', max_length=1000)),
                ('other_info', models.CharField(max_length=1000)),
                ('visibility', models.CharField(default='offlne', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='reading_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=1000)),
                ('staff_id', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=1000)),
                ('passport', models.CharField(default=' ', max_length=1000)),
                ('date_enrolled', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('acc_status', models.CharField(max_length=1000)),
                ('elib_duty', models.CharField(default='user', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=1000)),
                ('reg_num', models.CharField(max_length=50)),
                ('passport', models.CharField(default=' ', max_length=1000)),
                ('date_enrolled', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('acc_status', models.CharField(max_length=1000)),
            ],
        ),
    ]
